import { useState, useMemo, useEffect, useRef } from 'react';
import { Church, LayoutDashboard, HandCoins, ReceiptText, Users, ChartNoAxesCombined, Settings2, ChevronRight, ChevronLeft, CalendarDays, Download, ArrowUpRight, RefreshCw, Search, Wallet, Landmark, Banknote, Check, ShieldCheck, FileText, Eye, EyeOff, Printer, Info, ArrowRight, AlertCircle, FolderOpen, X, Menu, ExternalLink } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { TYPES, COLORS, MONTHS, emptyLedger, sampleLedger, won, week, sum, monthLabel, csvExport, fetchLedger, sourceURL } from './finance';
import './App.css';

const NAV = [
  { id: 'overview', label: '재정 대시보드', icon: LayoutDashboard },
  { id: 'income', label: '헌금 장부', icon: HandCoins },
  { id: 'expense', label: '지출 장부', icon: ReceiptText },
  { id: 'members', label: '성도별 조회', icon: Users },
  { id: 'report', label: '월간 결산', icon: ChartNoAxesCombined },
  { id: 'connection', label: '데이터 연결', icon: Settings2 },
];
const DESCRIPTIONS = { overview: '한 달의 헌금과 지출을 한눈에 확인하세요.', income: '헌금 내역을 종류와 결제 방식별로 살펴보세요.', expense: '지출 내역과 지급 방식을 함께 확인하세요.', members: '이름별 헌금 내역과 월 합계를 확인하세요.', report: '이월금부터 월말 잔액까지, 한 달의 재정을 정리합니다.', connection: '기존 구글 시트의 월별 연결과 확인 사항을 살펴보세요.' };
const titleOf = (view) => NAV.find(n => n.id === view)?.label || '재정 대시보드';

function Choice({ label, value, onChange, options, className = '' }) {
  return <select aria-label={label} value={value} onChange={e => onChange(e.target.value)} className={`choice ${className}`}>{options.map(o => typeof o === 'string' ? <option key={o} value={o}>{o}</option> : <option key={o.value} value={o.value}>{o.label}</option>)}</select>;
}
function Blank({ text = '해당하는 내역이 없습니다.', detail = '기간이나 검색 조건을 변경해 보세요.' }) {
  return <div className="blank"><FolderOpen size={34} /><strong>{text}</strong><p>{detail}</p></div>;
}
function Modal({ open, onClose, title, children, className = '' }) {
  const ref = useRef(null);
  useEffect(() => { if (open && !ref.current.open) ref.current.showModal(); else if (!open && ref.current.open) ref.current.close(); }, [open]);
  return <dialog ref={ref} className={`native-modal ${className}`} onCancel={onClose} onClose={onClose} onClick={e => { if (e.target === ref.current) onClose(); }} aria-label={title}><div className="modal-top"><h2>{title}</h2><button className="icon-button" aria-label="닫기" onClick={onClose}><X size={20} /></button></div>{children}</dialog>;
}

export default function App() {
  const [view, setView] = useState(() => NAV.some(n => n.id === location.hash.slice(1)) ? location.hash.slice(1) : 'overview');
  const [month, setMonth] = useState(MONTHS.at(-1));
  const [demo, setDemo] = useState(false);
  const [ledger, setLedger] = useState(emptyLedger);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [revision, setRevision] = useState(0);
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('전체');
  const [payment, setPayment] = useState('전체');
  const [weekFilter, setWeekFilter] = useState('전체');
  const [order, setOrder] = useState('최신순');
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState(null);
  const [person, setPerson] = useState(null);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [hideNames, setHideNames] = useState(() => { try { return localStorage.getItem('unjung-mask-names') === '1'; } catch { return false; } });
  const [feedback, setFeedback] = useState('');
  const [exporting, setExporting] = useState(false);
  useEffect(() => { const onHash = () => { const v = location.hash.slice(1); if (NAV.some(n => n.id === v)) { setView(v); resetFilters(); } }; window.addEventListener('hashchange', onHash); return () => window.removeEventListener('hashchange', onHash); }, []);
  useEffect(() => {
    let active = true; const controller = new AbortController(); let timedOut = false;
    setLoading(true); setError(''); setLedger(emptyLedger); setSelected(null); setPerson(null);
    if (demo) { setLedger(sampleLedger(month)); setLoading(false); return; }
    const timer = setTimeout(() => { timedOut = true; controller.abort(); }, 20000);
    fetchLedger(month, controller.signal).then(d => { if (active) setLedger(d); }).catch(e => { if (active) setError(timedOut ? '시트 응답이 지연되고 있습니다. 잠시 후 다시 시도해 주세요.' : e.message || '장부를 불러오지 못했습니다.'); }).finally(() => { clearTimeout(timer); if (active) setLoading(false); });
    return () => { active = false; clearTimeout(timer); controller.abort(); };
  }, [month, demo, revision]);
  useEffect(() => { setPage(1); }, [search, category, payment, weekFilter, month, view, order, demo]);
  useEffect(() => { if (!feedback) return; const t = setTimeout(() => setFeedback(''), 4500); return () => clearTimeout(t); }, [feedback]);
  function resetFilters() { setSearch(''); setCategory('전체'); setPayment('전체'); setWeekFilter('전체'); setPage(1); }
  function go(v) { setView(v); location.hash = v; resetFilters(); setMobileOpen(false); }
  function refresh() { setRevision(v => v + 1); }
  function mask() { const next = !hideNames; setHideNames(next); try { localStorage.setItem('unjung-mask-names', next ? '1' : '0'); } catch { /* Display preference is optional. */ } }
  const name = v => hideNames && v !== '무명' ? v.length > 1 ? v[0] + '•'.repeat(v.length - 1) : '•' : v;
  const data = ledger.entries;
  const incomes = useMemo(() => data.filter(r => r.kind === 'income'), [data]);
  const expenses = useMemo(() => data.filter(r => r.kind === 'expense'), [data]);
  const totalIncome = sum(incomes), totalExpense = sum(expenses), net = totalIncome - totalExpense;
  const cash = sum(incomes.filter(r => r.payment === '현금')), online = sum(incomes.filter(r => r.payment === '온라인'));
  const closing = ledger.opening === null ? null : ledger.opening + net;
  const difference = closing === null || ledger.reportedBalance === null ? null : closing - ledger.reportedBalance;
  const incomplete = !!error || !!ledger.warnings.length;
  const ready = !loading && !incomplete && ledger.sourceStatus === 'ok';
  const amount = v => loading || error ? '—' : v === null ? '미확인' : won(v);
  const chartData = Array.from({ length: Math.ceil(new Date(Number(month.slice(0, 4)), Number(month.slice(5)), 0).getDate() / 7) }, (_, i) => ({ name: `${i + 1}주차`, income: sum(incomes.filter(r => week(r.date) === i + 1)), expense: sum(expenses.filter(r => week(r.date) === i + 1)) }));
  const composition = [...TYPES, '기타수입'].map((t, i) => ({ name: t, value: sum(incomes.filter(r => r.category === t)), color: COLORS[i % COLORS.length] })).filter(r => r.value !== 0).sort((a, b) => b.value - a.value);
  const positiveTotal = sum(composition.filter(c => c.value > 0).map(c => ({ amount: c.value })));
  const allPeople = useMemo(() => { const map = new Map(); incomes.filter(r => r.category !== '기타수입').forEach(r => { const p = map.get(r.name) || { name: r.name, count: 0, amount: 0, last: '' }; p.count++; p.amount += r.amount; p.last = p.last > r.date ? p.last : r.date; map.set(r.name, p); }); return [...map.values()].sort((a, b) => a.name.localeCompare(b.name, 'ko')); }, [incomes]);
  const filtered = useMemo(() => {
    const records = view === 'expense' ? expenses : view === 'overview' ? data : incomes;
    return records.filter(r => (!search || r.name.includes(search) || r.note.includes(search)) && (category === '전체' || r.category === category) && (payment === '전체' || r.payment === payment) && (weekFilter === '전체' || `${week(r.date)}주차` === weekFilter)).sort((a, b) => order === '금액 높은순' ? b.amount - a.amount : order === '오래된순' ? a.date.localeCompare(b.date) : b.date.localeCompare(a.date));
  }, [view, expenses, incomes, data, search, category, payment, weekFilter, order]);
  const people = allPeople.filter(p => p.name.includes(search));
  const pages = Math.max(1, Math.ceil((view === 'members' ? people.length : filtered.length) / 10));
  const currentPage = Math.min(page, pages);
  const visible = view === 'overview' ? filtered.slice(0, 5) : filtered.slice((currentPage - 1) * 10, currentPage * 10);
  function exportMatrix(rows) { return [['날짜', '구분', '이름 또는 내역', '분류', '결제 방식', '금액(원)', '메모'], ...rows.map(r => [r.date, r.kind === 'income' ? '헌금·수입' : '지출', r.kind === 'income' ? name(r.name) : r.name, r.category, r.payment, r.amount, demo ? '예시 데이터' : r.note])]; }
  function exportRows(rows = filtered) {
    if (!ready) { setFeedback('원본 확인 사항을 해결한 후 내려받아 주세요.'); return; }
    const blob = new Blob([csvExport(exportMatrix(rows))], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `${demo ? '예시_' : ''}${month}_${titleOf(view)}.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 5000); setFeedback('CSV 파일을 내려받았습니다.');
  }
  async function exportExcel() {
    if (!ready || exporting) return;
    setExporting(true);
    try {
      const XLSX = await import('xlsx'); const book = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(book, XLSX.utils.aoa_to_sheet([['운정그리스도의교회', monthLabel(month)], ['자료 구분', demo ? '예시 데이터' : '구글 시트'], ['전월 이월금', ledger.opening ?? '미확인'], ['헌금·수입', totalIncome], ['지출', totalExpense], ['계산 잔액', closing ?? '미확인'], ['시트 잔액', ledger.reportedBalance ?? '미확인'], ['잔액 차이', difference ?? '미확인']]), '월간 결산');
      XLSX.utils.book_append_sheet(book, XLSX.utils.aoa_to_sheet(exportMatrix(incomes)), '헌금 내역'); XLSX.utils.book_append_sheet(book, XLSX.utils.aoa_to_sheet(exportMatrix(expenses)), '지출 내역');
      XLSX.writeFile(book, `${demo ? '예시_' : ''}${month}_교회재정결산.xlsx`); setFeedback('엑셀 결산 파일을 내려받았습니다.');
    } catch { setFeedback('엑셀 내보내기에 실패했습니다. CSV 내보내기를 이용해 주세요.'); } finally { setExporting(false); }
  }
  function renderTable(rows) { return <div className="table-scroll"><table><thead><tr><th>날짜</th><th>이름 / 내역</th><th>분류</th><th>결제 방식</th><th className="text-right">금액</th><th><span className="sr-only">상세 보기</span></th></tr></thead><tbody>{rows.map(r => <tr key={r.id}><td className="date-cell">{r.date.replaceAll('-', '.')}</td><td><button className="name-button" onClick={() => setSelected(r)}>{r.kind === 'income' ? name(r.name) : r.name}</button></td><td><span className={`tag ${r.kind === 'expense' ? 'tag-expense' : `tag-${Math.max(0, TYPES.indexOf(r.category)) % 4}`}`}>{r.category}</span></td><td><span className="payment-cell">{r.payment === '온라인' ? <Landmark size={14} /> : <Banknote size={14} />}{r.payment}</span></td><td className={`text-right amount-cell ${r.kind === 'expense' ? 'expense-text' : ''}`}>{r.kind === 'expense' ? '−' : ''}{won(r.amount)}<span> 원</span></td><td><button className="icon-button" aria-label={`${r.date} ${r.kind === 'income' ? name(r.name) : r.name} 상세 보기`} onClick={() => setSelected(r)}><ChevronRight size={16} /></button></td></tr>)}</tbody></table></div>; }
  function pager(count) { return <div className="table-footer"><span>총 <b>{count}</b>건{count > 0 && ` 중 ${(currentPage - 1) * 10 + 1}–${Math.min(currentPage * 10, count)}건`}</span><nav aria-label="페이지 이동" className="pager"><button className="icon-button" aria-label="이전 페이지" disabled={currentPage <= 1} onClick={() => setPage(currentPage - 1)}><ChevronLeft size={17} /></button><span className="page-number">{currentPage} / {pages}</span><button className="icon-button" aria-label="다음 페이지" disabled={currentPage >= pages} onClick={() => setPage(currentPage + 1)}><ChevronRight size={17} /></button></nav></div>; }
  function navContent() { return <><div className="brand"><div className="brand-icon"><Church size={27} strokeWidth={1.6} /></div><div><strong>운정그리스도의교회</strong><span>교회 재정관리</span></div></div><div className="nav-label">재정 관리</div><nav className="nav-list" aria-label="재정 관리 메뉴">{NAV.map(n => <button key={n.id} className="nav-button" data-active={view === n.id} aria-current={view === n.id ? 'page' : undefined} onClick={() => go(n.id)}><n.icon size={19} /><span>{n.label}</span>{view === n.id && <ChevronRight size={15} className="nav-arrow" />}</button>)}</nav><div className="sidebar-scripture"><div className="small-rule" /><p>각각 그 마음에 정한 대로<br />할 것이요</p><span>고린도후서 9:7</span></div><div className="sidebar-foot"><div className="shield-icon"><FileText size={19} /></div><div><strong>교회 재정 장부</strong><span>구글 시트 기준 · 조회용</span></div></div></>; }

  return <div className="finance-root"><aside className="desktop-sidebar">{navContent()}</aside><div className="app-shell"><header className="topbar"><div className="breadcrumb"><button aria-label="메뉴 열기" className="icon-button mobile-menu" onClick={() => setMobileOpen(true)}><Menu size={20} /></button><span>재정 관리</span><ChevronRight size={14} /><strong>{titleOf(view)}</strong></div><div className="topbar-actions"><button className="privacy-button" onClick={mask} aria-pressed={hideNames}>{hideNames ? <EyeOff size={17} /> : <Eye size={17} />}<span>{hideNames ? '이름 가림' : '이름 표시'}</span></button><div className="avatar">재정</div></div></header>
    <main className="workspace"><div className="page-heading"><div><div className="eyebrow">UNJEONG CHURCH · FINANCE</div><h1>{titleOf(view)}</h1><p>{DESCRIPTIONS[view]}</p></div><div className="heading-actions">{view === 'report' ? <button className="button" disabled={!ready} onClick={() => window.print()}><Printer size={16} />결산 인쇄</button> : <button className="button" disabled={!ready || !data.length} onClick={() => exportRows(view === 'overview' || view === 'connection' ? data : filtered)}><Download size={16} />CSV 내보내기</button>}<button className="button primary" disabled={loading} onClick={refresh}><RefreshCw size={16} className={loading ? 'spinning' : ''} />새로고침</button></div></div>
      <div className="period-bar"><div className="month-nav"><button className="icon-button" aria-label="이전 월" disabled={MONTHS.indexOf(month) === 0} onClick={() => setMonth(MONTHS[MONTHS.indexOf(month) - 1])}><ChevronLeft size={18} /></button><CalendarDays size={18} /><Choice label="조회 월" className="month-select" value={month} onChange={setMonth} options={MONTHS.map(m => ({ value: m, label: monthLabel(m) }))} /><button className="icon-button" aria-label="다음 월" disabled={MONTHS.indexOf(month) === MONTHS.length - 1} onClick={() => setMonth(MONTHS[MONTHS.indexOf(month) + 1])}><ChevronRight size={18} /></button><span className="period-separator" /><span className="period-dates">{month.replace('-', '.')} .01 – {new Date(Number(month.slice(0, 4)), Number(month.slice(5)), 0).getDate()}</span></div><span className="sync-status">{demo ? '예시 데이터' : loading ? '장부 불러오는 중…' : error ? '연결 확인 필요' : '구글 시트 연동'}</span></div>
      {demo && <div className="notice demo-notice"><Info size={18} /><span><b>예시 장부</b> · 아래 이름과 금액은 디자인 확인용 예시입니다.</span><button onClick={() => setDemo(false)}>실제 장부로 돌아가기 <ArrowRight size={14} /></button></div>}
      {error && <div className="notice error-notice" role="alert"><AlertCircle size={20} /><span>{error}</span><button onClick={refresh}>다시 시도</button><button onClick={() => setDemo(true)}>예시 보기</button></div>}
      {!!ledger.warnings.length && <div className="notice error-notice"><AlertCircle size={19} /><span>원본에 확인할 항목이 {ledger.warnings.length}개 있습니다. 일부 금액이 집계에서 제외될 수 있습니다.</span><button onClick={() => go('connection')}>확인하기</button></div>}
      {['overview', 'income', 'expense'].includes(view) && <section className="stats-grid" aria-label="검색과 무관한 월 전체 재정 요약"><article className="stat-card featured"><div className="stat-label">이번 달 헌금·수입<span className="stat-icon"><HandCoins size={20} /></span></div><div className="stat-amount">{amount(totalIncome)}<span>원</span></div><div className="stat-bottom"><span>{monthLabel(month)} 전체</span><span>{incomes.length}건</span></div></article><article className="stat-card"><div className="stat-label">이번 달 지출<span className="stat-icon rose"><ArrowUpRight size={20} /></span></div><div className="stat-amount">{amount(totalExpense)}<span>원</span></div><div className="stat-bottom"><span>{expenses.length}건의 내역</span><button onClick={() => go('expense')}>장부 보기 <ArrowRight size={13} /></button></div></article><article className="stat-card"><div className="stat-label">이월 포함 계산 잔액<span className="stat-icon blue"><Wallet size={20} /></span></div><div className="stat-amount">{amount(closing)}{closing !== null && <span>원</span>}</div><div className="stat-bottom"><span>이월금 {ledger.opening === null ? '미확인' : `${won(ledger.opening)}원`}</span></div></article><article className="stat-card"><div className="stat-label">헌금 참여 이름<span className="stat-icon gold"><Users size={20} /></span></div><div className="stat-amount">{loading || error ? '—' : allPeople.filter(p => p.name !== '무명').length}<span>명</span></div><div className="stat-bottom"><span>이름 기준 · 무명 제외</span><button onClick={() => go('members')}>성도별 조회 <ArrowRight size={13} /></button></div></article></section>}
      {view === 'overview' && <><section className="charts-grid"><article className="panel trend-panel"><div className="panel-heading"><div><h2>주차별 재정 흐름</h2><p>헌금·수입과 지출을 함께 비교합니다.</p></div><div className="legend"><span><i style={{ background: '#365d98' }} />헌금·수입</span><span><i style={{ background: '#c4a572' }} />지출</span></div></div><div className="trend-chart">{loading ? <div className="loading-block" /> : error ? <Blank text="데이터를 불러오지 못했습니다." detail="연결을 확인한 후 다시 시도해 주세요." /> : <ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ top: 12, right: 12, left: 0, bottom: 0 }}><defs><linearGradient id="incomeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#688bbe" stopOpacity={0.22} /><stop offset="100%" stopColor="#688bbe" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid strokeDasharray="4 5" vertical={false} stroke="#e8edf4" /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#7b8799', fontSize: 13 }} dy={9} /><YAxis tickFormatter={v => `${won(v / 10000)}만`} axisLine={false} tickLine={false} tick={{ fill: '#7b8799', fontSize: 12 }} width={58} /><Tooltip formatter={(v, n) => [`${won(Number(v))}원`, n === 'income' ? '헌금·수입' : '지출']} contentStyle={{ border: '1px solid #e5eaf1', borderRadius: 10, fontSize: 14 }} /><Area type="linear" dataKey="income" stroke="#365d98" strokeWidth={2.5} fill="url(#incomeFill)" dot={{ r: 3, fill: '#365d98', stroke: '#fff', strokeWidth: 2 }} /><Area type="linear" dataKey="expense" stroke="#b69662" strokeWidth={2} fill="transparent" strokeDasharray="5 4" dot={{ r: 3, fill: '#b69662', stroke: '#fff', strokeWidth: 2 }} /></AreaChart></ResponsiveContainer>}</div><div className="chart-foot">주차 기준: 1–7일 / 8–14일 / 15–21일 / 22–28일 / 29일 이후</div></article><article className="panel composition-panel"><div className="panel-heading"><h2>헌금 종류별 현황</h2><button className="text-button" onClick={() => go('income')}>전체 보기 <ChevronRight size={14} /></button></div><div className="composition-total"><span>총 헌금·수입</span><strong>{amount(totalIncome)}<small>원</small></strong></div><div className="composition-bar" aria-hidden="true">{composition.filter(c => c.value > 0).map(c => <div key={c.name} style={{ width: `${c.value / Math.max(positiveTotal, 1) * 100}%`, background: c.color }} />)}</div><div className="composition-list">{composition.length ? composition.map(c => <div key={c.name}><span><i style={{ background: c.color }} />{c.name}</span><b>{won(c.value)}<small>원</small></b><em>{totalIncome ? Math.round(c.value / totalIncome * 100) : 0}%</em></div>) : <p className="muted py-8">{loading ? '불러오는 중…' : error ? '조회할 수 없습니다.' : '등록된 헌금이 없습니다.'}</p>}</div></article></section>
        <section className="overview-lower"><article className="panel recent-panel"><div className="panel-heading"><div className="inline-heading"><h2>최근 거래 내역</h2><span className="count-badge">{data.length}</span></div><button className="text-button" onClick={() => go('income')}>장부 보기 <ArrowRight size={14} /></button></div>{loading ? <div className="loading-block table-loading" /> : visible.length ? renderTable(visible) : <Blank text={error ? '데이터를 불러오지 못했습니다.' : '등록된 거래가 없습니다.'} detail="연결 상태와 조회 월을 확인해 주세요." />}<div className="panel-bottom">{monthLabel(month)} 전체 헌금·수입 및 지출 기준</div></article><article className="panel payment-panel"><div className="panel-heading"><h2>헌금 결제 방식</h2></div>{[{ title: '온라인', amount: online, icon: Landmark, color: '#365d98' }, { title: '현금', amount: cash, icon: Banknote, color: '#b99a62' }].map(p => <div className="payment-summary" key={p.title}><div className="payment-title"><span><p.icon size={18} />{p.title}</span><b>{totalIncome ? Math.round(p.amount / totalIncome * 100) : 0}%</b></div><strong>{amount(p.amount)}<small> 원</small></strong><div className="meter"><div style={{ width: `${Math.max(0, Math.min(100, p.amount / Math.max(totalIncome, 1) * 100))}%`, background: p.color }} /></div></div>)}<div className={`reconcile-card ${difference === 0 ? 'reconciled' : ''}`}><ShieldCheck size={21} /><div><strong>{difference === 0 ? '시트 잔액 일치' : difference === null ? '잔액 확인 대기' : '시트 잔액 확인 필요'}</strong><span>{difference === 0 ? '원본 수입·지출 계산과 일치합니다.' : difference === null ? '이월금과 시트 잔액을 확인해 주세요.' : `계산 차이 ${won(difference)}원`}</span></div><button aria-label="월간 결산 보기" onClick={() => go('report')}><ChevronRight size={16} /></button></div></article></section></>}
      {(view === 'income' || view === 'expense') && <article className="panel ledger-panel"><div className="panel-heading"><div className="inline-heading"><h2>{view === 'income' ? '헌금·수입 내역' : '지출 내역'}</h2><span className="count-badge">{filtered.length}</span></div><Choice label="정렬" value={order} onChange={setOrder} options={['최신순', '오래된순', '금액 높은순']} /></div><div className="filterbar"><label className="search-input"><Search size={17} /><input aria-label="이름 또는 내역 검색" placeholder={view === 'expense' ? '지출 내역 검색' : '성도 이름 검색'} value={search} onChange={e => setSearch(e.target.value)} />{search && <button aria-label="검색 지우기" onClick={() => setSearch('')}><X size={15} /></button>}</label><Choice label="분류" value={category} onChange={setCategory} options={['전체', ...(view === 'expense' ? [...new Set(expenses.map(r => r.category))] : [...TYPES, '기타수입'])]} /><Choice label="결제 방식" value={payment} onChange={setPayment} options={[{ value: '전체', label: '결제 방식 전체' }, '현금', '온라인']} /><Choice label="주차" value={weekFilter} onChange={setWeekFilter} options={['전체', '1주차', '2주차', '3주차', '4주차', '5주차']} />{(search || category !== '전체' || payment !== '전체' || weekFilter !== '전체') && <button className="text-button" onClick={resetFilters}>초기화</button>}</div><div className="filtered-total"><span>조회 결과 <b>{filtered.length}</b>건</span><span>조회 합계 <strong>{amount(sum(filtered))}원</strong></span></div>{loading ? <div className="loading-block table-loading" /> : visible.length ? renderTable(visible) : <Blank />}{pager(filtered.length)}</article>}
      {view === 'members' && <><div className="notice"><Info size={17} /><span>구글 시트의 이름으로 묶어 표시합니다. 동명이인은 하나로 합산될 수 있으며 전체 등록 성도 수를 뜻하지 않습니다.</span></div><article className="panel"><div className="panel-heading"><div className="inline-heading"><h2>이름별 헌금 현황</h2><span className="count-badge">{allPeople.length}</span></div><label className="search-input"><Search size={17} /><input aria-label="성도 이름 검색" placeholder="성도 이름 검색" value={search} onChange={e => setSearch(e.target.value)} /></label></div>{people.length ? <div className="table-scroll"><table><thead><tr><th>이름</th><th>헌금 건수</th><th>최근 헌금일</th><th className="text-right">월 헌금 합계</th><th /></tr></thead><tbody>{people.slice((currentPage - 1) * 10, currentPage * 10).map((p, i) => <tr key={p.name}><td><button className="member-name" onClick={() => setPerson(p.name)}><span className={`member-avatar tone-${i % 3}`}>{hideNames ? '성도' : p.name.slice(0, 1)}</span>{name(p.name)}</button></td><td>{p.count}건</td><td className="date-cell">{p.last.replaceAll('-', '.')}</td><td className="amount-cell text-right">{won(p.amount)}<span> 원</span></td><td><button className="text-button" onClick={() => setPerson(p.name)}>내역 보기 <ChevronRight size={15} /></button></td></tr>)}</tbody></table></div> : loading ? <div className="loading-block table-loading" /> : <Blank />}{pager(people.length)}</article></>}
      {view === 'report' && <div className="report-wrap"><article className="panel report-paper"><div className="report-heading"><Church size={29} /><span>운정그리스도의교회</span><h2>{monthLabel(month)} 재정 결산</h2><p>{demo ? '예시 데이터 · 검토용' : incomplete ? '원본 확인 필요 · 미완료' : '조회용 결산 · 확정 전'}</p></div><div className="report-summary">{[{ label: '전월 이월금', v: ledger.opening }, { label: '당월 헌금·수입', v: totalIncome }, { label: '당월 지출', v: totalExpense }, { label: '계산 잔액', v: closing }].map(s => <div key={s.label}><span>{s.label}</span><strong>{amount(s.v)}{s.v !== null && <small> 원</small>}</strong></div>)}</div><div className="report-columns"><section><h3>헌금·수입 상세</h3>{[...TYPES, '기타수입'].map(t => <div className="report-line" key={t}><span>{t}</span><b>{amount(sum(incomes.filter(r => r.category === t)))}원</b></div>)}<div className="report-line total"><span>수입 합계</span><b>{amount(totalIncome)}원</b></div></section><section><h3>지출 상세</h3>{[...new Set(expenses.map(r => r.category))].map(t => <div className="report-line" key={t}><span>{t}</span><b>{amount(sum(expenses.filter(r => r.category === t)))}원</b></div>)}{!expenses.length && <p className="muted py-5">{loading ? '불러오는 중…' : error ? '조회할 수 없습니다.' : '지출 내역 없음'}</p>}<div className="report-line total"><span>지출 합계</span><b>{amount(totalExpense)}원</b></div></section></div><section className="report-check"><h3><ShieldCheck size={18} />잔액 검증</h3><div className="report-line"><span>구글 시트에 적힌 잔액</span><b>{ledger.reportedBalance === null ? '미확인' : `${won(ledger.reportedBalance)}원`}</b></div><div className="report-line"><span>이월금 + 헌금·수입 − 지출</span><b>{closing === null ? '미확인' : `${won(closing)}원`}</b></div><div className="report-line"><span>원본 잔액 차이</span><b className={difference === 0 ? 'success-text' : 'expense-text'}>{difference === null ? '미확인' : difference === 0 ? '일치' : `${won(difference)}원`}</b></div><p>계산 잔액은 시트의 이월금과 수입·지출을 반영한 금액입니다. 실제 계좌·현금 잔고와 별도로 대조해 주세요.</p></section><div className="report-signoff"><span>작성일 __________________</span><span>작성자 __________________</span><span>확인자 __________________</span></div></article><div className="report-actions"><button className="button" disabled={!ready || exporting} onClick={exportExcel}><Download size={17} />{exporting ? '파일 만드는 중…' : '엑셀 결산 내려받기'}</button><button className="button primary" disabled={!ready} onClick={() => window.print()}><Printer size={17} />인쇄 / PDF 저장</button></div></div>}
      {view === 'connection' && <div className="settings-grid"><article className="panel"><div className="panel-heading"><h2>구글 시트 연결</h2><span className="tag tag-0">읽기 전용</span></div><div className="settings-body"><div className="source-row"><div className="connection-icon"><FileText size={25} /></div><div><h3>기존 월별 재정 장부</h3><p>{monthLabel(MONTHS[0])} – {monthLabel(MONTHS.at(-1))} · {MONTHS.length}개 월별 시트</p></div></div><p>구글 시트의 헌금·지출·이월금을 읽어 표시합니다. 내역을 수정한 후 이 화면을 새로고침하면 반영됩니다.</p><div className="source-actions"><a className="button" href={sourceURL(month)} target="_blank" rel="noreferrer"><ExternalLink size={16} />현재 월 원본 보기</a><button className="button" onClick={refresh} disabled={loading}><RefreshCw size={16} />다시 불러오기</button></div><div className="settings-divider" /><div className="connection-facts"><span>현재 월 전체 내역 <b>{data.length}건</b></span><span>최근 조회 <b>{ledger.updatedAt ? new Date(ledger.updatedAt).toLocaleString('ko-KR', { timeZone: 'Asia/Seoul' }) : '—'}</b></span><span>현재 표시 자료 <b>{demo ? '예시 장부' : '실제 구글 시트'}</b></span></div><p className="small-note mt-7">이름 가림은 화면과 내려받기 표시를 바꾸는 기능입니다. 로그인이나 시트 접근 권한을 제한하는 기능은 아닙니다.</p></div></article><div><article className="panel"><div className="panel-heading"><h2>화면 미리보기</h2></div><div className="settings-body"><p>예시 장부에서 다양한 화면과 조회 기능을 살펴볼 수 있습니다. 예시 데이터는 실제 장부에 저장되지 않습니다.</p><button className="button" onClick={() => { setDemo(v => !v); resetFilters(); }}>{demo ? '실제 장부로 전환' : '예시 장부로 둘러보기'}<ArrowRight size={16} /></button></div></article><article className="panel mt-5"><div className="panel-heading"><h2>확인할 항목</h2></div><div className="settings-body">{ledger.warnings.length ? ledger.warnings.map((w, i) => <p key={i} className="warning-line"><AlertCircle size={16} />{w}</p>) : <p><Check size={18} className="inline mr-2 success-text" />{loading ? '원본 확인 중' : error ? '원본을 불러온 후 확인할 수 있습니다.' : '인식한 원본 형식에 확인 사항이 없습니다.'}</p>}<p className="small-note">신규 월은 월별 시트 설정에 추가하면 월 선택 목록에 자동으로 나타납니다.</p></div></article></div></div>}
      <footer className="workspace-footer"><span>운정그리스도의교회 <span className="footer-divider">|</span> 교회 재정관리</span><span>{demo ? '예시 장부' : `${monthLabel(month)} 장부`}</span></footer></main></div>
    <Modal open={mobileOpen} onClose={() => setMobileOpen(false)} title="메뉴" className="mobile-drawer">{navContent()}</Modal>
    <Modal open={!!selected} onClose={() => setSelected(null)} title="거래 상세">{selected && <div className="detail-body"><span className="tag tag-0">{selected.category}</span><h2>{selected.kind === 'income' ? name(selected.name) : selected.name}</h2><div className="detail-amount">{selected.kind === 'expense' ? '−' : ''}{won(selected.amount)}<small>원</small></div>{[{ label: '날짜', v: selected.date }, { label: '결제 방식', v: selected.payment }, { label: '자료', v: demo ? '예시 데이터' : '구글 시트' }, { label: '메모', v: selected.note || '—' }].map(r => <div className="detail-row" key={r.label}><span>{r.label}</span><b>{r.v}</b></div>)}</div>}</Modal>
    <Modal open={!!person} onClose={() => setPerson(null)} title={`${person ? name(person) : ''} 헌금 내역`}><div className="detail-body"><p className="muted">{monthLabel(month)} · 이름 기준 합산</p><div className="detail-amount">{won(sum(incomes.filter(r => r.name === person && r.category !== '기타수입')))}<small>원</small></div>{incomes.filter(r => r.name === person && r.category !== '기타수입').sort((a, b) => b.date.localeCompare(a.date)).map(r => <div className="person-detail-row" key={r.id}><div><b>{r.category}</b><span>{r.date} · {r.payment}</span></div><strong>{won(r.amount)}원</strong></div>)}</div></Modal>
    {feedback && <div className="toast-message" role="status">{feedback}<button className="icon-button" aria-label="알림 닫기" onClick={() => setFeedback('')}><X size={16} /></button></div>}
  </div>;
}